import { usePreferences } from "./preferences";
const labels: Record<string, [string, string]> = {
  jobFit: ["공고 적합도", "Job fit"],
  evidenceFidelity: ["근거 충실도", "Evidence fidelity"],
  readability: ["가독성", "Readability"],
  ats: ["채용 시스템 호환성", "ATS compatibility"],
  DISCOVERED: ["관심 공고", "Discovered"],
  PREPARING: ["준비 중", "Preparing"],
  READY: ["제출 준비", "Ready"],
  APPLIED: ["지원 완료", "Applied"],
  SCREENING: ["서류 심사", "Screening"],
  INTERVIEW: ["면접", "Interview"],
  OFFER: ["오퍼", "Offer"],
  ACCEPTED: ["수락", "Accepted"],
  REJECTED: ["불합격", "Rejected"],
  WITHDRAWN: ["철회", "Withdrawn"],
  DRAFT: ["초안", "Draft"],
  FINALIZED: ["확정", "Finalized"],
  ARCHIVED: ["보관됨", "Archived"],
  PENDING: ["검토 대기", "Pending"],
  APPROVED: ["승인됨", "Approved"],
  DENIED: ["거부됨", "Denied"],
  EXPIRED: ["만료됨", "Expired"],
  CONSUMED: ["승인 사용됨", "Consumed"],
  USER_PROVIDED: ["사용자 입력", "User provided"],
  VERIFIED: ["독립 검증됨", "Verified"],
  RULE_BASED: ["요구 기술 일치 분석", "Requirement matching"],
  AI_ASSISTED: ["AI 보조 분석", "AI assisted"],
  RESUME: ["이력서", "Resume"],
  PORTFOLIO: ["포트폴리오", "Portfolio"],
  COVER_LETTER: ["자기소개서", "Cover letter"],
  CAREER: ["경력", "Career"],
  EDUCATION: ["학력", "Education"],
  SKILL: ["기술", "Skill"],
  PROJECT: ["프로젝트", "Project"],
  GITHUB: ["GitHub", "GitHub"],
  TEXT: ["텍스트", "Text"],
  URL: ["URL", "URL"],
  DOM: ["브라우저 원문", "Browser text"],
  CLASSIC: ["기본형", "Classic"],
  MODERN: ["모던형", "Modern"],
  COMPACT: ["간결형", "Compact"],
  CUSTOM: ["개인 일정", "Personal"],
  DEADLINE: ["마감", "Deadline"],
  FOLLOW_UP: ["후속 작업", "Follow-up"],
  SUGGESTED: ["제안됨", "Suggested"],
  CONFIRMED: ["확인됨", "Confirmed"],
  DONE: ["완료", "Done"],
  DISMISSED: ["닫힘", "Dismissed"],
  SUPPORTED: ["근거 확인됨", "Supported"],
  NEEDS_REVIEW: ["근거 검토 필요", "Needs review"],
  UNSUPPORTED: ["근거 부족", "Unsupported"],
  LOCAL: ["내부 일정", "Local"],
  GOOGLE: ["Google", "Google"],
  APPROVAL_REQUIRED: ["승인 필요", "Approval required"],
  RUNNING: ["실행 중", "Running"],
  VERIFYING: ["검증 중", "Verifying"],
  FAILED: ["실패", "Failed"],
  UNKNOWN: ["상태 확인 필요", "Unknown"],
};
export const useLabel = () => {
  const locale = usePreferences((s) => s.locale);
  return (value: string) => labels[value]?.[locale === "ko" ? 0 : 1] || value;
};
